# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/storage/v1alpha/storage.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class DatasetState(betterproto.Enum):
    UNSPECIFIED = 0
    UPLOADING = 1
    READY = 2
    REMOVED = 3


@dataclass(eq=False, repr=False)
class ReserveDatasetRequest(betterproto.Message):
    dataset_name: str = betterproto.string_field(1)
    paths: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class UploadTarget(betterproto.Message):
    path: str = betterproto.string_field(1)
    upload_url: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ReserveDatasetResponse(betterproto.Message):
    uploads: List["UploadTarget"] = betterproto.message_field(1)
    expires_at: datetime = betterproto.message_field(2)
    dataset_id: str = betterproto.string_field(3)
    dataset_name: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class CommitDatasetRequest(betterproto.Message):
    dataset_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class CommitDatasetResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DeleteDatasetRequest(betterproto.Message):
    dataset_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DeleteDatasetResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListDatasetsRequest(betterproto.Message):
    prefix: str = betterproto.string_field(1)
    page_size: int = betterproto.uint32_field(2)
    offset: int = betterproto.uint32_field(3)
    page_token: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ListDatasetsResponse(betterproto.Message):
    datasets: List["DatasetSummary"] = betterproto.message_field(1)
    pagination: "Pagination" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class DatasetSummary(betterproto.Message):
    dataset_id: str = betterproto.string_field(1)
    dataset_name: str = betterproto.string_field(2)
    state: "DatasetState" = betterproto.enum_field(3)
    created_at: datetime = betterproto.message_field(4)
    expires_at: datetime = betterproto.message_field(5)
    content_length: int = betterproto.int64_field(6)


@dataclass(eq=False, repr=False)
class DatasetSelector(betterproto.Message):
    dataset_id: str = betterproto.string_field(1, group="selector")
    dataset_name: "DatasetNameSelector" = betterproto.message_field(2, group="selector")


@dataclass(eq=False, repr=False)
class DatasetNameSelector(betterproto.Message):
    name: str = betterproto.string_field(1)
    latest: bool = betterproto.bool_field(2)


@dataclass(eq=False, repr=False)
class GetDatasetContentsRequest(betterproto.Message):
    selector: "DatasetSelector" = betterproto.message_field(1)
    path_prefix: str = betterproto.string_field(2)
    glob_pattern: str = betterproto.string_field(3)
    page_size: int = betterproto.uint32_field(4)
    offset: int = betterproto.uint32_field(5)
    page_token: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class GetDatasetContentsResponse(betterproto.Message):
    files: List["FileEntry"] = betterproto.message_field(1)
    pagination: "Pagination" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class FileEntry(betterproto.Message):
    path: str = betterproto.string_field(1)
    size: int = betterproto.int64_field(2)
    last_modified: datetime = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class GetDownloadUrLsRequest(betterproto.Message):
    selector: "DatasetSelector" = betterproto.message_field(1)
    paths: "PathList" = betterproto.message_field(2, group="path_filter")
    glob_pattern: str = betterproto.string_field(3, group="path_filter")


@dataclass(eq=False, repr=False)
class PathList(betterproto.Message):
    paths: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DownloadTarget(betterproto.Message):
    path: str = betterproto.string_field(1)
    download_url: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GetDownloadUrLsResponse(betterproto.Message):
    downloads: List["DownloadTarget"] = betterproto.message_field(1)
    expires_at: datetime = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Pagination(betterproto.Message):
    next_offset: int = betterproto.uint32_field(1)
    has_more: bool = betterproto.bool_field(2)
    next_page_token: str = betterproto.string_field(3)


class BucketGatewayStub(betterproto.ServiceStub):
    async def reserve_dataset(
        self,
        reserve_dataset_request: "ReserveDatasetRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ReserveDatasetResponse":
        return await self._unary_unary(
            "/olcf.s3m.storage.v1alpha.BucketGateway/ReserveDataset",
            reserve_dataset_request,
            ReserveDatasetResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def commit_dataset(
        self,
        commit_dataset_request: "CommitDatasetRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "CommitDatasetResponse":
        return await self._unary_unary(
            "/olcf.s3m.storage.v1alpha.BucketGateway/CommitDataset",
            commit_dataset_request,
            CommitDatasetResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_dataset(
        self,
        delete_dataset_request: "DeleteDatasetRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeleteDatasetResponse":
        return await self._unary_unary(
            "/olcf.s3m.storage.v1alpha.BucketGateway/DeleteDataset",
            delete_dataset_request,
            DeleteDatasetResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_datasets(
        self,
        list_datasets_request: "ListDatasetsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListDatasetsResponse":
        return await self._unary_unary(
            "/olcf.s3m.storage.v1alpha.BucketGateway/ListDatasets",
            list_datasets_request,
            ListDatasetsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_dataset_contents(
        self,
        get_dataset_contents_request: "GetDatasetContentsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetDatasetContentsResponse":
        return await self._unary_unary(
            "/olcf.s3m.storage.v1alpha.BucketGateway/GetDatasetContents",
            get_dataset_contents_request,
            GetDatasetContentsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_download_ur_ls(
        self,
        get_download_ur_ls_request: "GetDownloadUrLsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetDownloadUrLsResponse":
        return await self._unary_unary(
            "/olcf.s3m.storage.v1alpha.BucketGateway/GetDownloadURLs",
            get_download_ur_ls_request,
            GetDownloadUrLsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class BucketGatewayBase(ServiceBase):

    async def reserve_dataset(
        self, reserve_dataset_request: "ReserveDatasetRequest"
    ) -> "ReserveDatasetResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def commit_dataset(
        self, commit_dataset_request: "CommitDatasetRequest"
    ) -> "CommitDatasetResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_dataset(
        self, delete_dataset_request: "DeleteDatasetRequest"
    ) -> "DeleteDatasetResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_datasets(
        self, list_datasets_request: "ListDatasetsRequest"
    ) -> "ListDatasetsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_dataset_contents(
        self, get_dataset_contents_request: "GetDatasetContentsRequest"
    ) -> "GetDatasetContentsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_download_ur_ls(
        self, get_download_ur_ls_request: "GetDownloadUrLsRequest"
    ) -> "GetDownloadUrLsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_reserve_dataset(
        self,
        stream: "grpclib.server.Stream[ReserveDatasetRequest, ReserveDatasetResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.reserve_dataset(request)
        await stream.send_message(response)

    async def __rpc_commit_dataset(
        self,
        stream: "grpclib.server.Stream[CommitDatasetRequest, CommitDatasetResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.commit_dataset(request)
        await stream.send_message(response)

    async def __rpc_delete_dataset(
        self,
        stream: "grpclib.server.Stream[DeleteDatasetRequest, DeleteDatasetResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_dataset(request)
        await stream.send_message(response)

    async def __rpc_list_datasets(
        self, stream: "grpclib.server.Stream[ListDatasetsRequest, ListDatasetsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_datasets(request)
        await stream.send_message(response)

    async def __rpc_get_dataset_contents(
        self,
        stream: "grpclib.server.Stream[GetDatasetContentsRequest, GetDatasetContentsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_dataset_contents(request)
        await stream.send_message(response)

    async def __rpc_get_download_ur_ls(
        self,
        stream: "grpclib.server.Stream[GetDownloadUrLsRequest, GetDownloadUrLsResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_download_ur_ls(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/olcf.s3m.storage.v1alpha.BucketGateway/ReserveDataset": grpclib.const.Handler(
                self.__rpc_reserve_dataset,
                grpclib.const.Cardinality.UNARY_UNARY,
                ReserveDatasetRequest,
                ReserveDatasetResponse,
            ),
            "/olcf.s3m.storage.v1alpha.BucketGateway/CommitDataset": grpclib.const.Handler(
                self.__rpc_commit_dataset,
                grpclib.const.Cardinality.UNARY_UNARY,
                CommitDatasetRequest,
                CommitDatasetResponse,
            ),
            "/olcf.s3m.storage.v1alpha.BucketGateway/DeleteDataset": grpclib.const.Handler(
                self.__rpc_delete_dataset,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteDatasetRequest,
                DeleteDatasetResponse,
            ),
            "/olcf.s3m.storage.v1alpha.BucketGateway/ListDatasets": grpclib.const.Handler(
                self.__rpc_list_datasets,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListDatasetsRequest,
                ListDatasetsResponse,
            ),
            "/olcf.s3m.storage.v1alpha.BucketGateway/GetDatasetContents": grpclib.const.Handler(
                self.__rpc_get_dataset_contents,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetDatasetContentsRequest,
                GetDatasetContentsResponse,
            ),
            "/olcf.s3m.storage.v1alpha.BucketGateway/GetDownloadURLs": grpclib.const.Handler(
                self.__rpc_get_download_ur_ls,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetDownloadUrLsRequest,
                GetDownloadUrLsResponse,
            ),
        }
