# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/status/v1alpha/status.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class ResourceMachineStatus(betterproto.Enum):
    UNSPECIFIED = 0
    OPERATIONAL = 1
    UNAVAILABLE = 2


class DowntimeMachineStatus(betterproto.Enum):
    UNSPECIFIED = 0
    UNAVAILABLE = 1


@dataclass(eq=False, repr=False)
class Resources(betterproto.Message):
    resources: List["Resource"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Resource(betterproto.Message):
    name: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    system_type: str = betterproto.string_field(3)
    security_enclave: str = betterproto.string_field(4)
    organization: str = betterproto.string_field(5)
    status: "ResourceMachineStatus" = betterproto.enum_field(6)
    annotations: Dict[str, str] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    downtime_schedule_available: bool = betterproto.bool_field(8)
    upcoming_downtimes: List["Downtime"] = betterproto.message_field(9)
    retrieved_at: datetime = betterproto.message_field(10)


@dataclass(eq=False, repr=False)
class GetResourceRequest(betterproto.Message):
    resource_name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class Downtimes(betterproto.Message):
    downtimes: List["Downtime"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Downtime(betterproto.Message):
    resource_name: str = betterproto.string_field(1)
    status: "DowntimeMachineStatus" = betterproto.enum_field(2)
    start: datetime = betterproto.message_field(3)
    end: datetime = betterproto.message_field(4)
    description: str = betterproto.string_field(5)
    attributes: "DowntimeAttributes" = betterproto.message_field(6)
    updated_at: datetime = betterproto.message_field(7)


@dataclass(eq=False, repr=False)
class DowntimeAttributes(betterproto.Message):
    scheduled: bool = betterproto.bool_field(1)
    reboot: bool = betterproto.bool_field(2)


class StatusStub(betterproto.ServiceStub):
    async def list_resources(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Resources":
        return await self._unary_unary(
            "/olcf.s3m.status.v1alpha.Status/ListResources",
            betterproto_lib_google_protobuf_empty,
            Resources,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_resource(
        self,
        get_resource_request: "GetResourceRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Resource":
        return await self._unary_unary(
            "/olcf.s3m.status.v1alpha.Status/GetResource",
            get_resource_request,
            Resource,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_downtimes_current(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Downtimes":
        return await self._unary_unary(
            "/olcf.s3m.status.v1alpha.Status/ListDowntimesCurrent",
            betterproto_lib_google_protobuf_empty,
            Downtimes,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_downtimes_upcoming(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "Downtimes":
        return await self._unary_unary(
            "/olcf.s3m.status.v1alpha.Status/ListDowntimesUpcoming",
            betterproto_lib_google_protobuf_empty,
            Downtimes,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class StatusBase(ServiceBase):

    async def list_resources(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "Resources":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_resource(
        self, get_resource_request: "GetResourceRequest"
    ) -> "Resource":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_downtimes_current(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "Downtimes":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_downtimes_upcoming(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "Downtimes":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_list_resources(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, Resources]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_resources(request)
        await stream.send_message(response)

    async def __rpc_get_resource(
        self, stream: "grpclib.server.Stream[GetResourceRequest, Resource]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_resource(request)
        await stream.send_message(response)

    async def __rpc_list_downtimes_current(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, Downtimes]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_downtimes_current(request)
        await stream.send_message(response)

    async def __rpc_list_downtimes_upcoming(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, Downtimes]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_downtimes_upcoming(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/olcf.s3m.status.v1alpha.Status/ListResources": grpclib.const.Handler(
                self.__rpc_list_resources,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                Resources,
            ),
            "/olcf.s3m.status.v1alpha.Status/GetResource": grpclib.const.Handler(
                self.__rpc_get_resource,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetResourceRequest,
                Resource,
            ),
            "/olcf.s3m.status.v1alpha.Status/ListDowntimesCurrent": grpclib.const.Handler(
                self.__rpc_list_downtimes_current,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                Downtimes,
            ),
            "/olcf.s3m.status.v1alpha.Status/ListDowntimesUpcoming": grpclib.const.Handler(
                self.__rpc_list_downtimes_upcoming,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                Downtimes,
            ),
        }
