# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/common/v1alpha/gerr.proto, proto/common/v1alpha/headers.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    Dict,
    Optional,
)

import betterproto


@dataclass(eq=False, repr=False)
class GerrError(betterproto.Message):
    code: int = betterproto.uint32_field(1)
    child: Optional["GerrErrorNode"] = betterproto.message_field(2, optional=True)
    message: str = betterproto.string_field(3)
    private: bool = betterproto.bool_field(4)
    public_message: Optional[str] = betterproto.string_field(5, optional=True)
    public_fields: Dict[str, str] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    private_fields: Dict[str, str] = betterproto.map_field(
        7, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )


@dataclass(eq=False, repr=False)
class GerrGoError(betterproto.Message):
    error: str = betterproto.string_field(1)
    kind: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class GerrErrorNode(betterproto.Message):
    error: "GerrError" = betterproto.message_field(1, group="node")
    go_error: "GerrGoError" = betterproto.message_field(2, group="node")


@dataclass(eq=False, repr=False)
class GerrPrivateDataMarker(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class HeaderParam(betterproto.Message):
    """
    Indicates that a HTTP header is available and optionally required
     for methods, and describes a friendly name for that parameter.
    """

    header: str = betterproto.string_field(1)
    param_name: str = betterproto.string_field(2)
    required: bool = betterproto.bool_field(3)
