# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/slurm/v0042/slurm.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import betterproto.lib.google.protobuf as betterproto_lib_google_protobuf
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class ErrorResp(betterproto.Message):
    error_number: int = betterproto.int32_field(1)
    error: str = betterproto.string_field(2)
    source: str = betterproto.string_field(3)
    description: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class WarningResp(betterproto.Message):
    warning: str = betterproto.string_field(1)
    source: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class Int32NoVal(betterproto.Message):
    set: bool = betterproto.bool_field(1)
    infinite: bool = betterproto.bool_field(2)
    number: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class Int64NoVal(betterproto.Message):
    set: bool = betterproto.bool_field(1)
    infinite: bool = betterproto.bool_field(2)
    number: int = betterproto.int64_field(3)


@dataclass(eq=False, repr=False)
class Uint32NoVal(betterproto.Message):
    set: bool = betterproto.bool_field(1)
    infinite: bool = betterproto.bool_field(2)
    number: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class Uint64NoVal(betterproto.Message):
    set: bool = betterproto.bool_field(1)
    infinite: bool = betterproto.bool_field(2)
    number: int = betterproto.uint64_field(3)


@dataclass(eq=False, repr=False)
class Float32NoVal(betterproto.Message):
    set: bool = betterproto.bool_field(1)
    infinite: bool = betterproto.bool_field(2)
    number: float = betterproto.float_field(3)


@dataclass(eq=False, repr=False)
class Float64NoVal(betterproto.Message):
    set: bool = betterproto.bool_field(1)
    infinite: bool = betterproto.bool_field(2)
    number: float = betterproto.double_field(3)


@dataclass(eq=False, repr=False)
class ExitCode(betterproto.Message):
    status: List[str] = betterproto.string_field(1)
    return_code: "Uint32NoVal" = betterproto.message_field(2)
    signal: "Signal" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class Signal(betterproto.Message):
    id: "Uint32NoVal" = betterproto.message_field(1)
    name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class MetaResp(betterproto.Message):
    plugin: "MetaPluginResp" = betterproto.message_field(1)
    slurm: "MetaSlurmResp" = betterproto.message_field(2)
    client: "MetaClientResp" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class MetaPluginResp(betterproto.Message):
    type: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    data_parser: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class MetaSlurmResp(betterproto.Message):
    version: "MetaSlurmVersionResp" = betterproto.message_field(1)
    release: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class MetaSlurmVersionResp(betterproto.Message):
    major: int = betterproto.int32_field(1)
    minor: int = betterproto.int32_field(2)
    micro: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class MetaClientResp(betterproto.Message):
    source: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DiagResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    statistics: "DiagStatistics" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class DiagStatistics(betterproto.Message):
    parts_packed: int = betterproto.int32_field(1)
    req_time: "Uint64NoVal" = betterproto.message_field(2)
    req_time_start: "Uint64NoVal" = betterproto.message_field(3)
    server_thread_count: int = betterproto.int32_field(4)
    agent_queue_size: int = betterproto.int32_field(5)
    agent_count: int = betterproto.int32_field(6)
    agent_thread_count: int = betterproto.int32_field(7)
    dbd_agent_queue_size: int = betterproto.int32_field(8)
    gettimeofday_latency: int = betterproto.int32_field(9)
    schedule_cycle_max: int = betterproto.int32_field(10)
    schedule_cycle_last: int = betterproto.int32_field(11)
    schedule_cycle_total: int = betterproto.int32_field(12)
    schedule_cycle_mean: int = betterproto.int64_field(13)
    schedule_cycle_mean_depth: int = betterproto.int64_field(14)
    schedule_cycle_per_minute: int = betterproto.int64_field(15)
    schedule_exit: "DiagScheduleExit" = betterproto.message_field(16)
    schedule_queue_length: int = betterproto.int32_field(17)
    jobs_submitted: int = betterproto.int32_field(18)
    jobs_started: int = betterproto.int32_field(19)
    jobs_completed: int = betterproto.int32_field(20)
    jobs_canceled: int = betterproto.int32_field(21)
    jobs_failed: int = betterproto.int32_field(22)
    jobs_pending: int = betterproto.int32_field(23)
    jobs_running: int = betterproto.int32_field(24)
    job_states_ts: "Uint64NoVal" = betterproto.message_field(25)
    bf_backfilled_jobs: int = betterproto.int32_field(26)
    bf_last_backfilled_jobs: int = betterproto.int32_field(27)
    bf_backfilled_het_jobs: int = betterproto.int32_field(28)
    bf_cycle_counter: int = betterproto.int32_field(29)
    bf_cycle_mean: int = betterproto.int64_field(30)
    bf_depth_mean: int = betterproto.int64_field(31)
    bf_depth_mean_try: int = betterproto.int64_field(32)
    bf_cycle_sum: int = betterproto.int64_field(33)
    bf_cycle_last: int = betterproto.int32_field(34)
    bf_last_depth: int = betterproto.int32_field(35)
    bf_last_depth_try: int = betterproto.int32_field(36)
    bf_depth_sum: int = betterproto.int32_field(37)
    bf_depth_try_sum: int = betterproto.int32_field(38)
    bf_queue_len: int = betterproto.int32_field(39)
    bf_queue_len_mean: int = betterproto.int64_field(40)
    bf_queue_len_sum: int = betterproto.int32_field(41)
    bf_table_size: int = betterproto.int32_field(42)
    bf_table_size_mean: int = betterproto.int64_field(43)
    bf_when_last_cycle: "Uint64NoVal" = betterproto.message_field(44)
    bf_active: bool = betterproto.bool_field(45)
    schedule_cycle_sum: int = betterproto.int32_field(46)
    rpcs_by_message_type: List["DiagRpcsMessage"] = betterproto.message_field(50)
    rpcs_by_user: List["DiagRpcsUser"] = betterproto.message_field(51)
    bf_exit: "DiagBfExit" = betterproto.message_field(52)


@dataclass(eq=False, repr=False)
class DiagRpcsMessage(betterproto.Message):
    message_type: str = betterproto.string_field(1)
    type_id: int = betterproto.int32_field(2)
    count: int = betterproto.int32_field(3)
    average_time: "Uint64NoVal" = betterproto.message_field(4)
    total_time: int = betterproto.int64_field(5)
    dropped: int = betterproto.int64_field(6)
    cycle_max: int = betterproto.int32_field(7)
    cycle_last: int = betterproto.int32_field(8)
    queued: int = betterproto.int32_field(9)


@dataclass(eq=False, repr=False)
class DiagRpcsUser(betterproto.Message):
    user_id: int = betterproto.int32_field(1)
    user: str = betterproto.string_field(2)
    count: int = betterproto.int32_field(3)
    total_time: int = betterproto.int64_field(4)
    average_time: "Uint64NoVal" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class DiagScheduleExit(betterproto.Message):
    end_job_queue: int = betterproto.int32_field(1)
    defult_queue_depth: int = betterproto.int32_field(2)
    max_job_start: int = betterproto.int32_field(3)
    max_rpc_cnt: int = betterproto.int32_field(4)
    max_sched_time: int = betterproto.int32_field(5)
    licenses: int = betterproto.int32_field(6)


@dataclass(eq=False, repr=False)
class DiagBfExit(betterproto.Message):
    end_job_queue: int = betterproto.int32_field(1)
    bf_max_job_start: int = betterproto.int32_field(2)
    bf_max_job_test: int = betterproto.int32_field(3)
    bf_max_time: int = betterproto.int32_field(4)
    bf_node_space_size: int = betterproto.int32_field(5)
    state_changed: int = betterproto.int32_field(6)


@dataclass(eq=False, repr=False)
class JobsResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    jobs: List["SlurmJobDescription"] = betterproto.message_field(4)
    last_backfill: "Uint64NoVal" = betterproto.message_field(5)
    last_update: "Uint64NoVal" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class SlurmJobDescription(betterproto.Message):
    account: str = betterproto.string_field(1)
    accrue_time: "Uint64NoVal" = betterproto.message_field(2)
    admin_comment: str = betterproto.string_field(3)
    allocating_node: str = betterproto.string_field(4)
    array_job_id: "Uint32NoVal" = betterproto.message_field(5)
    array_task_id: "Uint32NoVal" = betterproto.message_field(6)
    array_max_tasks: "Uint32NoVal" = betterproto.message_field(7)
    array_task_string: str = betterproto.string_field(8)
    association_id: int = betterproto.int32_field(9)
    batch_features: str = betterproto.string_field(10)
    batch_flag: bool = betterproto.bool_field(11)
    batch_host: str = betterproto.string_field(12)
    flags: List[str] = betterproto.string_field(13)
    burst_buffer: str = betterproto.string_field(14)
    burst_buffer_state: str = betterproto.string_field(15)
    cluster: str = betterproto.string_field(16)
    cluster_features: str = betterproto.string_field(17)
    command: str = betterproto.string_field(18)
    comment: str = betterproto.string_field(19)
    container: str = betterproto.string_field(20)
    container_id: str = betterproto.string_field(21)
    contiguous: bool = betterproto.bool_field(22)
    core_spec: int = betterproto.int32_field(23)
    thread_spec: int = betterproto.int32_field(24)
    cores_per_socket: "Uint32NoVal" = betterproto.message_field(25)
    billable_tres: "Float64NoVal" = betterproto.message_field(26)
    cpus_per_task: "Uint32NoVal" = betterproto.message_field(27)
    cpu_frequency_minimum: "Uint32NoVal" = betterproto.message_field(28)
    cpu_frequency_maximum: "Uint32NoVal" = betterproto.message_field(29)
    cpu_frequency_governor: "Uint32NoVal" = betterproto.message_field(30)
    cpus_per_tres: str = betterproto.string_field(31)
    cron: str = betterproto.string_field(32)
    deadline: "Uint64NoVal" = betterproto.message_field(33)
    delay_boot: "Uint32NoVal" = betterproto.message_field(34)
    dependency: str = betterproto.string_field(35)
    derived_exit_code: "ExitCode" = betterproto.message_field(36)
    eligible_time: "Uint64NoVal" = betterproto.message_field(37)
    end_time: "Uint64NoVal" = betterproto.message_field(38)
    excluded_nodes: str = betterproto.string_field(39)
    exit_code: "ExitCode" = betterproto.message_field(40)
    extra: str = betterproto.string_field(41)
    failed_node: str = betterproto.string_field(42)
    features: str = betterproto.string_field(43)
    federation_origin: str = betterproto.string_field(44)
    federation_siblings_active: str = betterproto.string_field(45)
    federation_siblings_viable: str = betterproto.string_field(46)
    gres_detail: List[str] = betterproto.string_field(47)
    group_id: int = betterproto.uint32_field(48)
    group_name: str = betterproto.string_field(49)
    het_job_id: "Uint32NoVal" = betterproto.message_field(50)
    het_job_id_set: str = betterproto.string_field(51)
    het_job_offset: "Uint32NoVal" = betterproto.message_field(52)
    job_id: int = betterproto.uint32_field(53)
    job_resources: "SlurmJobDescriptionResources" = betterproto.message_field(54)
    job_size_str: List[str] = betterproto.string_field(55)
    job_state: List[str] = betterproto.string_field(56)
    last_sched_evaluation: "Uint64NoVal" = betterproto.message_field(57)
    licenses: str = betterproto.string_field(58)
    mail_type: List[str] = betterproto.string_field(59)
    mail_user: str = betterproto.string_field(60)
    max_cpus: "Uint32NoVal" = betterproto.message_field(61)
    max_nodes: "Uint32NoVal" = betterproto.message_field(62)
    mcs_label: str = betterproto.string_field(63)
    memory_per_tres: str = betterproto.string_field(64)
    name: str = betterproto.string_field(65)
    network: str = betterproto.string_field(66)
    nodes: str = betterproto.string_field(67)
    nice: int = betterproto.int32_field(68)
    tasks_per_core: "Uint32NoVal" = betterproto.message_field(69)
    tasks_per_tres: "Uint32NoVal" = betterproto.message_field(70)
    tasks_per_node: "Uint32NoVal" = betterproto.message_field(71)
    tasks_per_socket: "Uint32NoVal" = betterproto.message_field(72)
    tasks_per_board: "Uint32NoVal" = betterproto.message_field(73)
    cpus: "Uint32NoVal" = betterproto.message_field(74)
    node_count: "Uint32NoVal" = betterproto.message_field(75)
    tasks: "Uint32NoVal" = betterproto.message_field(76)
    partition: str = betterproto.string_field(77)
    prefer: str = betterproto.string_field(78)
    memory_per_cpu: "Uint64NoVal" = betterproto.message_field(79)
    memory_per_node: "Uint64NoVal" = betterproto.message_field(80)
    minimum_cpus_per_node: "Uint32NoVal" = betterproto.message_field(81)
    minimum_tmp_disk_per_node: "Uint32NoVal" = betterproto.message_field(82)
    preempt_time: "Uint64NoVal" = betterproto.message_field(83)
    preemptable_time: "Uint64NoVal" = betterproto.message_field(84)
    pre_sus_time: "Uint64NoVal" = betterproto.message_field(85)
    hold: bool = betterproto.bool_field(86)
    priority: "Uint32NoVal" = betterproto.message_field(87)
    profile: List[str] = betterproto.string_field(89)
    qos: str = betterproto.string_field(90)
    reboot: bool = betterproto.bool_field(91)
    required_nodes: str = betterproto.string_field(92)
    required_switches: int = betterproto.int32_field(93)
    requeue: bool = betterproto.bool_field(94)
    resize_time: "Uint64NoVal" = betterproto.message_field(95)
    restart_cnt: int = betterproto.int32_field(96)
    resv_name: str = betterproto.string_field(97)
    scheduled_nodes: str = betterproto.string_field(98)
    selinux_context: str = betterproto.string_field(99)
    shared: List[str] = betterproto.string_field(100)
    sockets_per_board: int = betterproto.int32_field(101)
    sockets_per_node: "Uint32NoVal" = betterproto.message_field(102)
    start_time: "Uint64NoVal" = betterproto.message_field(103)
    state_description: str = betterproto.string_field(104)
    state_reason: str = betterproto.string_field(105)
    standard_error: str = betterproto.string_field(106)
    standard_input: str = betterproto.string_field(107)
    standard_output: str = betterproto.string_field(108)
    submit_time: "Uint64NoVal" = betterproto.message_field(109)
    suspend_time: "Uint64NoVal" = betterproto.message_field(110)
    system_comment: str = betterproto.string_field(111)
    time_limit: "Uint32NoVal" = betterproto.message_field(112)
    time_minimum: "Uint32NoVal" = betterproto.message_field(113)
    threads_per_core: "Uint32NoVal" = betterproto.message_field(114)
    tres_bind: str = betterproto.string_field(115)
    tres_per_job: str = betterproto.string_field(116)
    tres_per_node: str = betterproto.string_field(117)
    tres_per_socket: str = betterproto.string_field(118)
    tres_per_task: str = betterproto.string_field(119)
    tres_req_str: str = betterproto.string_field(120)
    tres_alloc_str: str = betterproto.string_field(121)
    user_id: int = betterproto.uint32_field(122)
    user_name: str = betterproto.string_field(123)
    maximum_switch_wait_time: int = betterproto.int32_field(124)
    wckey: str = betterproto.string_field(125)
    current_working_directory: str = betterproto.string_field(126)


@dataclass(eq=False, repr=False)
class SlurmJobDescriptionResources(betterproto.Message):
    select_type: List[str] = betterproto.string_field(1)
    cpus: int = betterproto.uint32_field(2)
    threads_per_core: "Uint32NoVal" = betterproto.message_field(3)
    nodes: "SlurmJobDescriptionResourcesNodes" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class SlurmJobDescriptionResourcesNodes(betterproto.Message):
    count: int = betterproto.int32_field(1)
    list: str = betterproto.string_field(2)
    whole: bool = betterproto.bool_field(3)
    job_resources: List[str] = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class JobIdReq(betterproto.Message):
    job_id: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class JobIdResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    jobs: List["SlurmDbJobDescription"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescription(betterproto.Message):
    account: str = betterproto.string_field(1)
    comment: "SlurmDbJobDescriptionComment" = betterproto.message_field(2)
    allocation_nodes: int = betterproto.int32_field(3)
    array: "SlurmDbJobDescriptionArray" = betterproto.message_field(4)
    association: "SlurmDbJobDescriptionAssociation" = betterproto.message_field(5)
    block: str = betterproto.string_field(6)
    cluster: str = betterproto.string_field(7)
    constraints: str = betterproto.string_field(8)
    container: str = betterproto.string_field(9)
    derived_exit_code: "ExitCode" = betterproto.message_field(10)
    time: "SlurmDbJobDescriptionTime" = betterproto.message_field(11)
    exit_code: "ExitCode" = betterproto.message_field(12)
    extra: str = betterproto.string_field(13)
    failed_node: str = betterproto.string_field(14)
    flags: List[str] = betterproto.string_field(15)
    gruop: str = betterproto.string_field(16)
    het: "SlurmDbJobDescriptionHet" = betterproto.message_field(17)
    job_id: int = betterproto.int32_field(18)
    name: str = betterproto.string_field(19)
    licenses: str = betterproto.string_field(20)
    nodes: str = betterproto.string_field(21)
    partition: str = betterproto.string_field(22)
    hold: bool = betterproto.bool_field(23)
    priority: "Uint32NoVal" = betterproto.message_field(24)
    qos: str = betterproto.string_field(25)
    qosreq: str = betterproto.string_field(26)
    required: "SlurmDbJobDescriptionRequired" = betterproto.message_field(27)
    kill_request_user: str = betterproto.string_field(28)
    restart_cnt: int = betterproto.int32_field(29)
    reservation: "SlurmDbJobDescriptionReservation" = betterproto.message_field(30)
    script: str = betterproto.string_field(31)
    stdin_expanded: str = betterproto.string_field(32)
    stdout_expanded: str = betterproto.string_field(33)
    stderr_expanded: str = betterproto.string_field(34)
    stdout: str = betterproto.string_field(35)
    stderr: str = betterproto.string_field(36)
    stdin: str = betterproto.string_field(37)
    state: "SlurmDbJobDescriptionState" = betterproto.message_field(38)
    steps: List["SlurmDbJobDescriptionStep"] = betterproto.message_field(39)
    submit_line: str = betterproto.string_field(40)
    used_gres: str = betterproto.string_field(42)
    user: str = betterproto.string_field(43)
    working_directory: str = betterproto.string_field(45)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionArray(betterproto.Message):
    job_id: int = betterproto.int32_field(1)
    task_id: "Uint32NoVal" = betterproto.message_field(2)
    task: str = betterproto.string_field(3)
    limits: "SlurmDbJobDescriptionArrayLimits" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionArrayLimits(betterproto.Message):
    max: "SlurmDbJobDescriptionArrayLimitsMax" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionArrayLimitsMax(betterproto.Message):
    running: "SlurmDbJobDescriptionArrayLimitsMaxRunning" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionArrayLimitsMaxRunning(betterproto.Message):
    tasks: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionAssociation(betterproto.Message):
    account: str = betterproto.string_field(1)
    cluster: str = betterproto.string_field(2)
    partition: str = betterproto.string_field(3)
    user: str = betterproto.string_field(4)
    id: int = betterproto.int32_field(5)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionComment(betterproto.Message):
    administrator: str = betterproto.string_field(1)
    job: str = betterproto.string_field(2)
    system: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionHet(betterproto.Message):
    job_id: int = betterproto.int32_field(1)
    job_offset: "Uint32NoVal" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionTime(betterproto.Message):
    elapsed: int = betterproto.int32_field(1)
    start: int = betterproto.int64_field(2)
    end: int = betterproto.int64_field(3)
    suspended: int = betterproto.int32_field(4)
    planned: "Uint64NoVal" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionRequired(betterproto.Message):
    cp_us: int = betterproto.int32_field(1)
    memory_per_cpu: "Uint64NoVal" = betterproto.message_field(2)
    memory_per_node: "Uint64NoVal" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionReservation(betterproto.Message):
    id: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionState(betterproto.Message):
    current: List[str] = betterproto.string_field(1)
    reason: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStep(betterproto.Message):
    time: "SlurmDbJobDescriptionStepStepTime" = betterproto.message_field(1)
    exit_code: "ExitCode" = betterproto.message_field(2)
    nodes: "SlurmDbJobDescriptionStepNodes" = betterproto.message_field(3)
    tasks: "SlurmDbJobDescriptionStepTasks" = betterproto.message_field(4)
    cpu: "SlurmDbJobDescriptionStepCpu" = betterproto.message_field(5)
    kill_request_user: str = betterproto.string_field(6)
    state: List[str] = betterproto.string_field(7)
    step: "SlurmDbJobDescriptionStepStep" = betterproto.message_field(8)
    task: "SlurmDbJobDescriptionStepTask" = betterproto.message_field(9)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStepNodes(betterproto.Message):
    count: int = betterproto.int32_field(1)
    range: str = betterproto.string_field(2)
    list: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStepTasks(betterproto.Message):
    count: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStepCpu(betterproto.Message):
    requested_frequency: "SlurmDbJobDescriptionStepCpuRequestedFrequency" = (
        betterproto.message_field(1)
    )
    governor: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStepCpuRequestedFrequency(betterproto.Message):
    min: "Uint32NoVal" = betterproto.message_field(1)
    max: "Uint32NoVal" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStepStep(betterproto.Message):
    id: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStepTask(betterproto.Message):
    distribution: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class SlurmDbJobDescriptionStepStepTime(betterproto.Message):
    elapsed: int = betterproto.int32_field(1)
    end: "Uint64NoVal" = betterproto.message_field(2)
    start: "Uint64NoVal" = betterproto.message_field(3)
    suspended: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class JobSubmitReq(betterproto.Message):
    job: "JobSubmitReqJobDescription" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class JobSubmitReqJobDescription(betterproto.Message):
    account: str = betterproto.string_field(1)
    begin_time: "Uint64NoVal" = betterproto.message_field(9)
    comment: Optional[str] = betterproto.string_field(14, optional=True)
    environment: List[str] = betterproto.string_field(28)
    licenses: Optional[str] = betterproto.string_field(38, optional=True)
    name: str = betterproto.string_field(45)
    tasks: Optional[int] = betterproto.int32_field(48, optional=True)
    partition: str = betterproto.string_field(53)
    distribution_plane_size: "Uint32NoVal" = betterproto.message_field(54)
    priority: "Uint32NoVal" = betterproto.message_field(57)
    qos: Optional[str] = betterproto.string_field(59, optional=True)
    reservation: Optional[str] = betterproto.string_field(63, optional=True)
    script: str = betterproto.string_field(64)
    time_limit: "Uint32NoVal" = betterproto.message_field(69)
    time_minimum: "Uint32NoVal" = betterproto.message_field(70)
    wait_all_nodes: bool = betterproto.bool_field(78)
    current_working_directory: str = betterproto.string_field(82)
    cpus_per_task: Optional[int] = betterproto.int32_field(83, optional=True)
    minimum_cpus: Optional[int] = betterproto.int32_field(84, optional=True)
    maximum_cpus: Optional[int] = betterproto.int32_field(85, optional=True)
    nodes: Optional[str] = betterproto.string_field(86, optional=True)
    minimum_nodes: Optional[int] = betterproto.int32_field(87, optional=True)
    maximum_nodes: Optional[int] = betterproto.int32_field(88, optional=True)
    minimum_boards_per_node: Optional[int] = betterproto.int32_field(89, optional=True)
    minimum_sockets_per_board: Optional[int] = betterproto.int32_field(
        90, optional=True
    )
    sockets_per_node: Optional[int] = betterproto.int32_field(91, optional=True)
    threads_per_core: Optional[int] = betterproto.int32_field(92, optional=True)
    tasks_per_node: Optional[int] = betterproto.int32_field(93, optional=True)
    tasks_per_socket: Optional[int] = betterproto.int32_field(94, optional=True)
    tasks_per_core: Optional[int] = betterproto.int32_field(95, optional=True)
    tasks_per_board: Optional[int] = betterproto.int32_field(96, optional=True)
    ntasks_per_tres: Optional[int] = betterproto.int32_field(97, optional=True)
    minimum_cpus_per_node: Optional[int] = betterproto.int32_field(98, optional=True)
    memory_per_cpu: "Uint64NoVal" = betterproto.message_field(99)
    memory_per_node: "Uint64NoVal" = betterproto.message_field(100)
    standard_input: Optional[str] = betterproto.string_field(105, optional=True)
    standard_output: Optional[str] = betterproto.string_field(106, optional=True)
    standard_error: Optional[str] = betterproto.string_field(107, optional=True)


@dataclass(eq=False, repr=False)
class JobSubmitReqJobDescriptionCrontab(betterproto.Message):
    minute: str = betterproto.string_field(1)
    hour: str = betterproto.string_field(2)
    day_of_month: str = betterproto.string_field(3)
    month: str = betterproto.string_field(4)
    day_of_week: str = betterproto.string_field(5)
    specification: str = betterproto.string_field(6)
    command: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class JobSubmitReqJobDescriptionRLimits(betterproto.Message):
    cpu: "Uint64NoVal" = betterproto.message_field(1)
    fsize: "Uint64NoVal" = betterproto.message_field(2)
    data: "Uint64NoVal" = betterproto.message_field(3)
    stack: "Uint64NoVal" = betterproto.message_field(4)
    core: "Uint64NoVal" = betterproto.message_field(5)
    rss: "Uint64NoVal" = betterproto.message_field(6)
    nproc: "Uint64NoVal" = betterproto.message_field(7)
    nofile: "Uint64NoVal" = betterproto.message_field(8)
    memlock: "Uint64NoVal" = betterproto.message_field(9)
    as_: "Uint64NoVal" = betterproto.message_field(10)


@dataclass(eq=False, repr=False)
class JobSubmitResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    job_id: Optional[int] = betterproto.int32_field(5, optional=True)
    step_id: Optional[str] = betterproto.string_field(6, optional=True)
    job_submit_user_msg: Optional[str] = betterproto.string_field(7, optional=True)


@dataclass(eq=False, repr=False)
class DeleteJobReq(betterproto.Message):
    job_id: str = betterproto.string_field(1)
    signal: str = betterproto.string_field(2)
    flags: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class DeleteJobResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    status: List["DeleteJobRespStatus"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class DeleteJobRespStatus(betterproto.Message):
    error: "DeleteJobRespStatusError" = betterproto.message_field(1)
    step_id: str = betterproto.string_field(2)
    job_id: "Uint32NoVal" = betterproto.message_field(3)
    federation: "DeleteJobRespStatusFederation" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class DeleteJobRespStatusError(betterproto.Message):
    string: str = betterproto.string_field(1)
    code: int = betterproto.int32_field(2)
    message: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class DeleteJobRespStatusFederation(betterproto.Message):
    sibling: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class NodesResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    nodes: List["SlurmNodeDescription"] = betterproto.message_field(4)
    last_update: "Uint64NoVal" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class SlurmNodeDescription(betterproto.Message):
    architecture: str = betterproto.string_field(1)
    burstbuffer_network_address: str = betterproto.string_field(2)
    boards: int = betterproto.int32_field(3)
    boot_time: "Uint64NoVal" = betterproto.message_field(4)
    cluster_name: str = betterproto.string_field(5)
    cores: int = betterproto.int32_field(6)
    specialized_cores: int = betterproto.int32_field(7)
    cpu_binding: int = betterproto.int32_field(8)
    cpu_load: int = betterproto.int32_field(9)
    free_mem: "Uint64NoVal" = betterproto.message_field(10)
    cpus: int = betterproto.int32_field(11)
    effective_cpus: int = betterproto.int32_field(12)
    specialized_cpus: str = betterproto.string_field(13)
    energy: "SlurmNodeDescriptionEnegery" = betterproto.message_field(14)
    extra: str = betterproto.string_field(15)
    features: List[str] = betterproto.string_field(16)
    active_features: List[str] = betterproto.string_field(17)
    gpu_spec: str = betterproto.string_field(18)
    gres: str = betterproto.string_field(19)
    gres_drained: str = betterproto.string_field(20)
    gres_used: str = betterproto.string_field(21)
    instance_id: str = betterproto.string_field(22)
    instance_type: str = betterproto.string_field(23)
    last_busy: "Uint64NoVal" = betterproto.message_field(24)
    mcs_label: str = betterproto.string_field(25)
    specialized_memory: int = betterproto.int64_field(26)
    name: str = betterproto.string_field(27)
    next_state_after_reboot: List[str] = betterproto.string_field(28)
    address: str = betterproto.string_field(29)
    hostname: str = betterproto.string_field(30)
    state: List[str] = betterproto.string_field(31)
    operating_system: str = betterproto.string_field(32)
    owner: str = betterproto.string_field(33)
    partitions: List[str] = betterproto.string_field(34)
    port: int = betterproto.int32_field(35)
    real_memory: int = betterproto.int64_field(36)
    res_cores_per_gpu: int = betterproto.int32_field(37)
    comment: str = betterproto.string_field(38)
    reason: str = betterproto.string_field(39)
    reason_changed_at: "Uint32NoVal" = betterproto.message_field(40)
    reason_set_by_user: str = betterproto.string_field(41)
    resume_after: "Uint64NoVal" = betterproto.message_field(42)
    reservation: str = betterproto.string_field(43)
    alloc_memory: int = betterproto.int64_field(44)
    alloc_cpus: int = betterproto.int32_field(45)
    alloc_idle_cpus: int = betterproto.int32_field(46)
    tres_used: str = betterproto.string_field(47)
    tres_weighted: float = betterproto.double_field(48)
    slurmd_start_time: "Uint64NoVal" = betterproto.message_field(49)
    sockets: int = betterproto.int32_field(50)
    threads: int = betterproto.int32_field(51)
    temporary_disk: int = betterproto.int32_field(52)
    weight: int = betterproto.int32_field(53)
    tres: str = betterproto.string_field(54)
    version: str = betterproto.string_field(55)


@dataclass(eq=False, repr=False)
class SlurmNodeDescriptionEnegery(betterproto.Message):
    average_watts: int = betterproto.int32_field(1)
    base_consumed_energy: int = betterproto.int64_field(2)
    consumed_energy: int = betterproto.int64_field(3)
    current_watts: "Uint32NoVal" = betterproto.message_field(4)
    previous_consumed_energy: int = betterproto.int64_field(5)
    last_collected: int = betterproto.int64_field(6)


@dataclass(eq=False, repr=False)
class ControllerPingResp(betterproto.Message):
    hostname: str = betterproto.string_field(1)
    pinged: str = betterproto.string_field(2)
    latency: int = betterproto.int64_field(3)
    mode: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class PingResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    pings: List["ControllerPingResp"] = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class PartitionsResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    partitions: List["SlurmPartitionDescription"] = betterproto.message_field(4)
    last_update: "Uint64NoVal" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescription(betterproto.Message):
    nodes: "SlurmPartitionDescriptionNodes" = betterproto.message_field(1)
    accounts: "SlurmPartitionDescriptionAccounts" = betterproto.message_field(2)
    groups: "SlurmPartitionDescriptionGroups" = betterproto.message_field(3)
    qos: "SlurmPartitionDescriptionQos" = betterproto.message_field(4)
    alternate: str = betterproto.string_field(5)
    tres: "SlurmPartitionDescriptionTres" = betterproto.message_field(6)
    cluster: str = betterproto.string_field(7)
    select_type: List[str] = betterproto.string_field(8)
    cpus: "SlurmPartitionDescriptionCpus" = betterproto.message_field(9)
    defaults: "SlurmPartitionDescriptionDefaults" = betterproto.message_field(10)
    grace_time: int = betterproto.int32_field(11)
    maximums: "SlurmPartitionDescriptionMaximums" = betterproto.message_field(12)
    minimums: "SlurmPartitionDescriptionMinimums" = betterproto.message_field(13)
    name: str = betterproto.string_field(14)
    node_sets: str = betterproto.string_field(15)
    priority: "SlurmPartitionDescriptionPriority" = betterproto.message_field(16)
    timeouts: "SlurmPartitionDescriptionTimeouts" = betterproto.message_field(17)
    partition: "SlurmPartitionDescriptionPartition" = betterproto.message_field(18)
    suspend_time: "Uint32NoVal" = betterproto.message_field(19)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionNodes(betterproto.Message):
    allowed_configuration: str = betterproto.string_field(1)
    configured: str = betterproto.string_field(2)
    total: int = betterproto.int32_field(3)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionAccounts(betterproto.Message):
    allowed: str = betterproto.string_field(1)
    deny: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionGroups(betterproto.Message):
    allowed: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionQos(betterproto.Message):
    allowed: str = betterproto.string_field(1)
    deny: str = betterproto.string_field(2)
    assigned: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionTres(betterproto.Message):
    billing_weights: str = betterproto.string_field(1)
    configured: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionCpus(betterproto.Message):
    task_binding: int = betterproto.int32_field(1)
    total: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionDefaults(betterproto.Message):
    memory_per_cpu: int = betterproto.int64_field(1)
    partition_memory_per_cpu: "Uint64NoVal" = betterproto.message_field(2)
    partition_memory_per_node: "Uint64NoVal" = betterproto.message_field(3)
    time: "Uint32NoVal" = betterproto.message_field(4)
    job: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionMaximums(betterproto.Message):
    cpus_per_node: "Uint32NoVal" = betterproto.message_field(1)
    cpus_per_socket: "Uint32NoVal" = betterproto.message_field(2)
    memory_per_cpu: int = betterproto.int64_field(3)
    partition_memory_per_cpu: "Uint64NoVal" = betterproto.message_field(4)
    partition_memory_per_node: "Uint64NoVal" = betterproto.message_field(5)
    nodes: "Uint32NoVal" = betterproto.message_field(6)
    shares: int = betterproto.int32_field(7)
    oversubscribe: "SlurmPartitionDescriptionMaximumsOversubscribe" = (
        betterproto.message_field(8)
    )
    time: "Uint32NoVal" = betterproto.message_field(9)
    over_time_limit: "Uint32NoVal" = betterproto.message_field(10)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionMaximumsOversubscribe(betterproto.Message):
    jobs: int = betterproto.int32_field(1)
    flags: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionMinimums(betterproto.Message):
    nodes: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionPriority(betterproto.Message):
    job_factor: int = betterproto.int32_field(1)
    tier: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionTimeouts(betterproto.Message):
    resume: "Uint32NoVal" = betterproto.message_field(1)
    suspend: "Uint32NoVal" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class SlurmPartitionDescriptionPartition(betterproto.Message):
    state: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ReservationsResp(betterproto.Message):
    meta: "MetaResp" = betterproto.message_field(1)
    errors: List["ErrorResp"] = betterproto.message_field(2)
    warnings: List["WarningResp"] = betterproto.message_field(3)
    reservations: List["Reservation"] = betterproto.message_field(4)
    last_update: "Uint64NoVal" = betterproto.message_field(6)


@dataclass(eq=False, repr=False)
class Reservation(betterproto.Message):
    accounts: str = betterproto.string_field(1)
    burst_buffer: str = betterproto.string_field(2)
    core_count: int = betterproto.int32_field(3)
    core_specializations: List[str] = betterproto.string_field(4)
    end_time: "Uint64NoVal" = betterproto.message_field(5)
    features: str = betterproto.string_field(6)
    flags: List[str] = betterproto.string_field(7)
    groups: str = betterproto.string_field(8)
    licenses: str = betterproto.string_field(9)
    max_start_delay: int = betterproto.int32_field(10)
    name: str = betterproto.string_field(11)
    node_count: int = betterproto.int32_field(12)
    node_list: str = betterproto.string_field(13)
    partition: str = betterproto.string_field(14)
    purge_completed: "Uint32NoVal" = betterproto.message_field(15)
    start_time: "Uint64NoVal" = betterproto.message_field(16)
    watts: "Uint32NoVal" = betterproto.message_field(17)
    tres: str = betterproto.string_field(18)
    users: str = betterproto.string_field(19)


class SlurmIndirectStub(betterproto.ServiceStub):
    async def ping(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PingResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/Ping",
            betterproto_lib_google_protobuf_empty,
            PingResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_diag(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DiagResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetDiag",
            betterproto_lib_google_protobuf_empty,
            DiagResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_job(
        self,
        job_id_req: "JobIdReq",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "JobIdResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetJob",
            job_id_req,
            JobIdResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_jobs(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "JobsResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetJobs",
            betterproto_lib_google_protobuf_empty,
            JobsResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def post_job_submit(
        self,
        job_submit_req: "JobSubmitReq",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "JobSubmitResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/PostJobSubmit",
            job_submit_req,
            JobSubmitResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_job(
        self,
        delete_job_req: "DeleteJobReq",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeleteJobResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/DeleteJob",
            delete_job_req,
            DeleteJobResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_nodes(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "NodesResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetNodes",
            betterproto_lib_google_protobuf_empty,
            NodesResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_partitions(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PartitionsResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetPartitions",
            betterproto_lib_google_protobuf_empty,
            PartitionsResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_reservations(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ReservationsResp":
        return await self._unary_unary(
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetReservations",
            betterproto_lib_google_protobuf_empty,
            ReservationsResp,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SlurmIndirectBase(ServiceBase):

    async def ping(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "PingResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_diag(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "DiagResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_job(self, job_id_req: "JobIdReq") -> "JobIdResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_jobs(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "JobsResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def post_job_submit(self, job_submit_req: "JobSubmitReq") -> "JobSubmitResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_job(self, delete_job_req: "DeleteJobReq") -> "DeleteJobResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_nodes(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "NodesResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_partitions(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "PartitionsResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_reservations(
        self,
        betterproto_lib_google_protobuf_empty: "betterproto_lib_google_protobuf.Empty",
    ) -> "ReservationsResp":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_ping(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, PingResp]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.ping(request)
        await stream.send_message(response)

    async def __rpc_get_diag(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, DiagResp]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_diag(request)
        await stream.send_message(response)

    async def __rpc_get_job(
        self, stream: "grpclib.server.Stream[JobIdReq, JobIdResp]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_job(request)
        await stream.send_message(response)

    async def __rpc_get_jobs(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, JobsResp]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_jobs(request)
        await stream.send_message(response)

    async def __rpc_post_job_submit(
        self, stream: "grpclib.server.Stream[JobSubmitReq, JobSubmitResp]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.post_job_submit(request)
        await stream.send_message(response)

    async def __rpc_delete_job(
        self, stream: "grpclib.server.Stream[DeleteJobReq, DeleteJobResp]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_job(request)
        await stream.send_message(response)

    async def __rpc_get_nodes(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, NodesResp]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_nodes(request)
        await stream.send_message(response)

    async def __rpc_get_partitions(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, PartitionsResp]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_partitions(request)
        await stream.send_message(response)

    async def __rpc_get_reservations(
        self,
        stream: "grpclib.server.Stream[betterproto_lib_google_protobuf.Empty, ReservationsResp]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_reservations(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/olcf.s3m.slurm.v0042.SlurmIndirect/Ping": grpclib.const.Handler(
                self.__rpc_ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                PingResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetDiag": grpclib.const.Handler(
                self.__rpc_get_diag,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                DiagResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetJob": grpclib.const.Handler(
                self.__rpc_get_job,
                grpclib.const.Cardinality.UNARY_UNARY,
                JobIdReq,
                JobIdResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetJobs": grpclib.const.Handler(
                self.__rpc_get_jobs,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                JobsResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/PostJobSubmit": grpclib.const.Handler(
                self.__rpc_post_job_submit,
                grpclib.const.Cardinality.UNARY_UNARY,
                JobSubmitReq,
                JobSubmitResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/DeleteJob": grpclib.const.Handler(
                self.__rpc_delete_job,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteJobReq,
                DeleteJobResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetNodes": grpclib.const.Handler(
                self.__rpc_get_nodes,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                NodesResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetPartitions": grpclib.const.Handler(
                self.__rpc_get_partitions,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                PartitionsResp,
            ),
            "/olcf.s3m.slurm.v0042.SlurmIndirect/GetReservations": grpclib.const.Handler(
                self.__rpc_get_reservations,
                grpclib.const.Cardinality.UNARY_UNARY,
                betterproto_lib_google_protobuf.Empty,
                ReservationsResp,
            ),
        }
