# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/tms/v1/control.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class IntrospectAuthTokenRequest(betterproto.Message):
    grpc_permissions: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class IntrospectAuthTokenResponse(betterproto.Message):
    token: "TokenDetailsIntrospective" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class RevokeAuthTokenRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class RevokeAuthTokenResponse(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class TokenDetailsIntrospective(betterproto.Message):
    username: str = betterproto.string_field(1)
    project: str = betterproto.string_field(2)
    permissions: List[str] = betterproto.string_field(3)
    planned_expiration: datetime = betterproto.message_field(4)
    security_enclave: str = betterproto.string_field(5)
    description: str = betterproto.string_field(6)
    one_time_token: bool = betterproto.bool_field(7)
    delayed_start: bool = betterproto.bool_field(8)
    delay_date: datetime = betterproto.message_field(9)
    owner_name: str = betterproto.string_field(10)
    grpc_permissions: List["GrpcPermissions"] = betterproto.message_field(11)
    extensions: int = betterproto.int32_field(12)


@dataclass(eq=False, repr=False)
class GrpcPermissions(betterproto.Message):
    path: str = betterproto.string_field(1)
    permission: str = betterproto.string_field(2)


class TokenControlStub(betterproto.ServiceStub):
    async def introspect_auth_token(
        self,
        introspect_auth_token_request: "IntrospectAuthTokenRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "IntrospectAuthTokenResponse":
        return await self._unary_unary(
            "/olcf.s3m.tms.v1.TokenControl/IntrospectAuthToken",
            introspect_auth_token_request,
            IntrospectAuthTokenResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def revoke_auth_token(
        self,
        revoke_auth_token_request: "RevokeAuthTokenRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "RevokeAuthTokenResponse":
        return await self._unary_unary(
            "/olcf.s3m.tms.v1.TokenControl/RevokeAuthToken",
            revoke_auth_token_request,
            RevokeAuthTokenResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class TokenControlBase(ServiceBase):

    async def introspect_auth_token(
        self, introspect_auth_token_request: "IntrospectAuthTokenRequest"
    ) -> "IntrospectAuthTokenResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def revoke_auth_token(
        self, revoke_auth_token_request: "RevokeAuthTokenRequest"
    ) -> "RevokeAuthTokenResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_introspect_auth_token(
        self,
        stream: "grpclib.server.Stream[IntrospectAuthTokenRequest, IntrospectAuthTokenResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.introspect_auth_token(request)
        await stream.send_message(response)

    async def __rpc_revoke_auth_token(
        self,
        stream: "grpclib.server.Stream[RevokeAuthTokenRequest, RevokeAuthTokenResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.revoke_auth_token(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/olcf.s3m.tms.v1.TokenControl/IntrospectAuthToken": grpclib.const.Handler(
                self.__rpc_introspect_auth_token,
                grpclib.const.Cardinality.UNARY_UNARY,
                IntrospectAuthTokenRequest,
                IntrospectAuthTokenResponse,
            ),
            "/olcf.s3m.tms.v1.TokenControl/RevokeAuthToken": grpclib.const.Handler(
                self.__rpc_revoke_auth_token,
                grpclib.const.Cardinality.UNARY_UNARY,
                RevokeAuthTokenRequest,
                RevokeAuthTokenResponse,
            ),
        }
