# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/streaming/v1alpha/common.proto, proto/streaming/v1alpha/rabbitmq.proto, proto/streaming/v1alpha/redis.proto, proto/streaming/v1alpha/streaming.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from datetime import datetime
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase

if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class BackendResourceOption(betterproto.Message):
    key: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    min: int = betterproto.int32_field(3)
    max: int = betterproto.int32_field(4)
    default: int = betterproto.int32_field(5)


@dataclass(eq=False, repr=False)
class BackendFeatureFlag(betterproto.Message):
    key: str = betterproto.string_field(1)
    description: str = betterproto.string_field(2)
    default: bool = betterproto.bool_field(3)


@dataclass(eq=False, repr=False)
class AppEndpoints(betterproto.Message):
    addresses: List[str] = betterproto.string_field(1)
    ports: Dict[str, int] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_UINT32
    )


@dataclass(eq=False, repr=False)
class Lifetime(betterproto.Message):
    provisioned_at: datetime = betterproto.message_field(1)
    extended_at: datetime = betterproto.message_field(2)
    seconds_lifetime: int = betterproto.uint32_field(3)
    seconds_remaining: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class RabbitMqClusterSummary(betterproto.Message):
    kind: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    sync_status: str = betterproto.string_field(3)
    health_status: str = betterproto.string_field(4)
    lifetime: "Lifetime" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class RabbitMqCluster(betterproto.Message):
    kind: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    sync_status: str = betterproto.string_field(3)
    health_status: str = betterproto.string_field(4)
    lifetime: "Lifetime" = betterproto.message_field(5)
    resource_settings: Dict[str, int] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_INT32
    )
    username: Optional[str] = betterproto.string_field(7, optional=True)
    password: Optional[str] = betterproto.string_field(8, optional=True)
    amqps_url: Optional[str] = betterproto.string_field(9, optional=True)
    mgmt_url: Optional[str] = betterproto.string_field(10, optional=True)
    feature_flags: Dict[str, bool] = betterproto.map_field(
        11, betterproto.TYPE_STRING, betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class ProvisionRabbitMqClusterRequest(betterproto.Message):
    kind: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    resource_settings: Dict[str, int] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_INT32
    )
    feature_flags: Dict[str, bool] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class ProvisionRabbitMqClusterResponse(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)
    amqps_url: str = betterproto.string_field(3)
    mgmt_url: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ListRabbitMqClustersRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListRabbitMqClustersResponse(betterproto.Message):
    clusters: List["RabbitMqClusterSummary"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetRabbitMqClusterRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetRabbitMqClusterResponse(betterproto.Message):
    cluster: "RabbitMqCluster" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class DeleteRabbitMqClusterRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DeleteRabbitMqClusterResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class ExtendRabbitMqClusterLifeRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ExtendRabbitMqClusterLifeResponse(betterproto.Message):
    lifetime: "Lifetime" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class RedisClusterSummary(betterproto.Message):
    kind: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    sync_status: str = betterproto.string_field(3)
    health_status: str = betterproto.string_field(4)
    lifetime: "Lifetime" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class RedisCluster(betterproto.Message):
    kind: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    sync_status: str = betterproto.string_field(3)
    health_status: str = betterproto.string_field(4)
    lifetime: "Lifetime" = betterproto.message_field(5)
    resource_settings: Dict[str, int] = betterproto.map_field(
        6, betterproto.TYPE_STRING, betterproto.TYPE_INT32
    )
    username: Optional[str] = betterproto.string_field(7, optional=True)
    password: Optional[str] = betterproto.string_field(8, optional=True)
    redis_url: Optional[str] = betterproto.string_field(9, optional=True)
    feature_flags: Dict[str, bool] = betterproto.map_field(
        10, betterproto.TYPE_STRING, betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class ProvisionRedisClusterRequest(betterproto.Message):
    kind: str = betterproto.string_field(1)
    name: str = betterproto.string_field(2)
    resource_settings: Dict[str, int] = betterproto.map_field(
        3, betterproto.TYPE_STRING, betterproto.TYPE_INT32
    )
    feature_flags: Dict[str, bool] = betterproto.map_field(
        4, betterproto.TYPE_STRING, betterproto.TYPE_BOOL
    )


@dataclass(eq=False, repr=False)
class ProvisionRedisClusterResponse(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)
    url: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ListRedisClustersRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListRedisClustersResponse(betterproto.Message):
    clusters: List["RedisClusterSummary"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetRedisClusterRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GetRedisClusterResponse(betterproto.Message):
    cluster: "RedisCluster" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class DeleteRedisClusterRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class DeleteRedisClusterResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass(eq=False, repr=False)
class ExtendRedisClusterLifeRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class ExtendRedisClusterLifeResponse(betterproto.Message):
    lifetime: "Lifetime" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class ListBackendsRequest(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ListBackendsResponse(betterproto.Message):
    backends: List["Backend"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Backend(betterproto.Message):
    engine: str = betterproto.string_field(1)
    kind: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    resource_options: List["BackendResourceOption"] = betterproto.message_field(4)
    feature_flags: List["BackendFeatureFlag"] = betterproto.message_field(5)


class StreamingStub(betterproto.ServiceStub):
    async def list_backends(
        self,
        list_backends_request: "ListBackendsRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListBackendsResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.Streaming/ListBackends",
            list_backends_request,
            ListBackendsResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class RabbitMqStreamingStub(betterproto.ServiceStub):
    async def provision_rabbit_mq_cluster(
        self,
        provision_rabbit_mq_cluster_request: "ProvisionRabbitMqClusterRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ProvisionRabbitMqClusterResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ProvisionRabbitMQCluster",
            provision_rabbit_mq_cluster_request,
            ProvisionRabbitMqClusterResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_rabbit_mq_clusters(
        self,
        list_rabbit_mq_clusters_request: "ListRabbitMqClustersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListRabbitMqClustersResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ListRabbitMQClusters",
            list_rabbit_mq_clusters_request,
            ListRabbitMqClustersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_rabbit_mq_cluster(
        self,
        get_rabbit_mq_cluster_request: "GetRabbitMqClusterRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetRabbitMqClusterResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/GetRabbitMQCluster",
            get_rabbit_mq_cluster_request,
            GetRabbitMqClusterResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_rabbit_mq_cluster(
        self,
        delete_rabbit_mq_cluster_request: "DeleteRabbitMqClusterRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeleteRabbitMqClusterResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/DeleteRabbitMQCluster",
            delete_rabbit_mq_cluster_request,
            DeleteRabbitMqClusterResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def extend_rabbit_mq_cluster_life(
        self,
        extend_rabbit_mq_cluster_life_request: "ExtendRabbitMqClusterLifeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ExtendRabbitMqClusterLifeResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ExtendRabbitMQClusterLife",
            extend_rabbit_mq_cluster_life_request,
            ExtendRabbitMqClusterLifeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class RedisStreamingStub(betterproto.ServiceStub):
    async def provision_redis_cluster(
        self,
        provision_redis_cluster_request: "ProvisionRedisClusterRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ProvisionRedisClusterResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/ProvisionRedisCluster",
            provision_redis_cluster_request,
            ProvisionRedisClusterResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def list_redis_clusters(
        self,
        list_redis_clusters_request: "ListRedisClustersRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ListRedisClustersResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/ListRedisClusters",
            list_redis_clusters_request,
            ListRedisClustersResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def get_redis_cluster(
        self,
        get_redis_cluster_request: "GetRedisClusterRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "GetRedisClusterResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/GetRedisCluster",
            get_redis_cluster_request,
            GetRedisClusterResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def delete_redis_cluster(
        self,
        delete_redis_cluster_request: "DeleteRedisClusterRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "DeleteRedisClusterResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/DeleteRedisCluster",
            delete_redis_cluster_request,
            DeleteRedisClusterResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def extend_redis_cluster_life(
        self,
        extend_redis_cluster_life_request: "ExtendRedisClusterLifeRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ExtendRedisClusterLifeResponse":
        return await self._unary_unary(
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/ExtendRedisClusterLife",
            extend_redis_cluster_life_request,
            ExtendRedisClusterLifeResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class StreamingBase(ServiceBase):

    async def list_backends(
        self, list_backends_request: "ListBackendsRequest"
    ) -> "ListBackendsResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_list_backends(
        self, stream: "grpclib.server.Stream[ListBackendsRequest, ListBackendsResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_backends(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/olcf.s3m.streaming.v1alpha.Streaming/ListBackends": grpclib.const.Handler(
                self.__rpc_list_backends,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListBackendsRequest,
                ListBackendsResponse,
            ),
        }


class RabbitMqStreamingBase(ServiceBase):

    async def provision_rabbit_mq_cluster(
        self, provision_rabbit_mq_cluster_request: "ProvisionRabbitMqClusterRequest"
    ) -> "ProvisionRabbitMqClusterResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_rabbit_mq_clusters(
        self, list_rabbit_mq_clusters_request: "ListRabbitMqClustersRequest"
    ) -> "ListRabbitMqClustersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_rabbit_mq_cluster(
        self, get_rabbit_mq_cluster_request: "GetRabbitMqClusterRequest"
    ) -> "GetRabbitMqClusterResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_rabbit_mq_cluster(
        self, delete_rabbit_mq_cluster_request: "DeleteRabbitMqClusterRequest"
    ) -> "DeleteRabbitMqClusterResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def extend_rabbit_mq_cluster_life(
        self, extend_rabbit_mq_cluster_life_request: "ExtendRabbitMqClusterLifeRequest"
    ) -> "ExtendRabbitMqClusterLifeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_provision_rabbit_mq_cluster(
        self,
        stream: "grpclib.server.Stream[ProvisionRabbitMqClusterRequest, ProvisionRabbitMqClusterResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.provision_rabbit_mq_cluster(request)
        await stream.send_message(response)

    async def __rpc_list_rabbit_mq_clusters(
        self,
        stream: "grpclib.server.Stream[ListRabbitMqClustersRequest, ListRabbitMqClustersResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_rabbit_mq_clusters(request)
        await stream.send_message(response)

    async def __rpc_get_rabbit_mq_cluster(
        self,
        stream: "grpclib.server.Stream[GetRabbitMqClusterRequest, GetRabbitMqClusterResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_rabbit_mq_cluster(request)
        await stream.send_message(response)

    async def __rpc_delete_rabbit_mq_cluster(
        self,
        stream: "grpclib.server.Stream[DeleteRabbitMqClusterRequest, DeleteRabbitMqClusterResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_rabbit_mq_cluster(request)
        await stream.send_message(response)

    async def __rpc_extend_rabbit_mq_cluster_life(
        self,
        stream: "grpclib.server.Stream[ExtendRabbitMqClusterLifeRequest, ExtendRabbitMqClusterLifeResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.extend_rabbit_mq_cluster_life(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ProvisionRabbitMQCluster": grpclib.const.Handler(
                self.__rpc_provision_rabbit_mq_cluster,
                grpclib.const.Cardinality.UNARY_UNARY,
                ProvisionRabbitMqClusterRequest,
                ProvisionRabbitMqClusterResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ListRabbitMQClusters": grpclib.const.Handler(
                self.__rpc_list_rabbit_mq_clusters,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListRabbitMqClustersRequest,
                ListRabbitMqClustersResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/GetRabbitMQCluster": grpclib.const.Handler(
                self.__rpc_get_rabbit_mq_cluster,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetRabbitMqClusterRequest,
                GetRabbitMqClusterResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/DeleteRabbitMQCluster": grpclib.const.Handler(
                self.__rpc_delete_rabbit_mq_cluster,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteRabbitMqClusterRequest,
                DeleteRabbitMqClusterResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RabbitMQStreaming/ExtendRabbitMQClusterLife": grpclib.const.Handler(
                self.__rpc_extend_rabbit_mq_cluster_life,
                grpclib.const.Cardinality.UNARY_UNARY,
                ExtendRabbitMqClusterLifeRequest,
                ExtendRabbitMqClusterLifeResponse,
            ),
        }


class RedisStreamingBase(ServiceBase):

    async def provision_redis_cluster(
        self, provision_redis_cluster_request: "ProvisionRedisClusterRequest"
    ) -> "ProvisionRedisClusterResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def list_redis_clusters(
        self, list_redis_clusters_request: "ListRedisClustersRequest"
    ) -> "ListRedisClustersResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def get_redis_cluster(
        self, get_redis_cluster_request: "GetRedisClusterRequest"
    ) -> "GetRedisClusterResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def delete_redis_cluster(
        self, delete_redis_cluster_request: "DeleteRedisClusterRequest"
    ) -> "DeleteRedisClusterResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def extend_redis_cluster_life(
        self, extend_redis_cluster_life_request: "ExtendRedisClusterLifeRequest"
    ) -> "ExtendRedisClusterLifeResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_provision_redis_cluster(
        self,
        stream: "grpclib.server.Stream[ProvisionRedisClusterRequest, ProvisionRedisClusterResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.provision_redis_cluster(request)
        await stream.send_message(response)

    async def __rpc_list_redis_clusters(
        self,
        stream: "grpclib.server.Stream[ListRedisClustersRequest, ListRedisClustersResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.list_redis_clusters(request)
        await stream.send_message(response)

    async def __rpc_get_redis_cluster(
        self,
        stream: "grpclib.server.Stream[GetRedisClusterRequest, GetRedisClusterResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.get_redis_cluster(request)
        await stream.send_message(response)

    async def __rpc_delete_redis_cluster(
        self,
        stream: "grpclib.server.Stream[DeleteRedisClusterRequest, DeleteRedisClusterResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.delete_redis_cluster(request)
        await stream.send_message(response)

    async def __rpc_extend_redis_cluster_life(
        self,
        stream: "grpclib.server.Stream[ExtendRedisClusterLifeRequest, ExtendRedisClusterLifeResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.extend_redis_cluster_life(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/ProvisionRedisCluster": grpclib.const.Handler(
                self.__rpc_provision_redis_cluster,
                grpclib.const.Cardinality.UNARY_UNARY,
                ProvisionRedisClusterRequest,
                ProvisionRedisClusterResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/ListRedisClusters": grpclib.const.Handler(
                self.__rpc_list_redis_clusters,
                grpclib.const.Cardinality.UNARY_UNARY,
                ListRedisClustersRequest,
                ListRedisClustersResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/GetRedisCluster": grpclib.const.Handler(
                self.__rpc_get_redis_cluster,
                grpclib.const.Cardinality.UNARY_UNARY,
                GetRedisClusterRequest,
                GetRedisClusterResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/DeleteRedisCluster": grpclib.const.Handler(
                self.__rpc_delete_redis_cluster,
                grpclib.const.Cardinality.UNARY_UNARY,
                DeleteRedisClusterRequest,
                DeleteRedisClusterResponse,
            ),
            "/olcf.s3m.streaming.v1alpha.RedisStreaming/ExtendRedisClusterLife": grpclib.const.Handler(
                self.__rpc_extend_redis_cluster_life,
                grpclib.const.Cardinality.UNARY_UNARY,
                ExtendRedisClusterLifeRequest,
                ExtendRedisClusterLifeResponse,
            ),
        }
